/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.auritylab.kotlin.apple.signin

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
